### ISSUE TITLE
Does not work with alpine linux

### ISSUE THREAD

**Issue by shyim** [sass/dart-sass-embedded#106] opened 2022-08-12 11:04 UTC
Hey,

the built binaries are not working with Alpine Linux

**Comment by nex3** [comment] 2022-08-12 20:56
Duplicate of https://github.com/sass/embedded-host-node/issues/155. Consider adding a :+1: react to https://github.com/dart-lang/sdk/issues/40906 if you'd like to see Dart support musl-libc.

**Closed as not planned by nex3** 2022-08-12 20:56 UTC

**Comment by ntkme** [comment] 2022-08-12 21:16
Since https://github.com/dart-lang/sdk/issues/40906 has been closed, I would recommend open a new issue on dart-sdk asking formal support for musl-libc. How dart team will take it is up to them however :-)

**Comment by nex3** [comment] 2022-08-12 22:18
I don't think it's likely to be very useful to open a new issue requesting something that was already requested by a closed issue. They've made a decision not to support this; the best we can do for now is to show how valuable it would be to users if they reconsidered that decision.

**Comment by ntkme** [comment] 2022-08-13 02:21
The answer was provided over 2 years ago when the community don’t have enough interest over dart on musl, but now that has changed (literally the most asked question for dart-sass-embedded), thus I think it is worth open a new issue and see if the team will change their mind this time given the demand.

The problem of thumb up a closed issue is that GitHub will not send notifications for reactions, and no one is going to look at closed one. Therefore I think open a new one and citing the new and legit demand from sass community may help us get some traction.

**Comment by shyim** [comment] 2022-08-13 08:24
It looks like https://github.com/dart-lang/sdk/issues/32894 has progress. It would definitively help integrate sass then into other languages. Dart Sass Embedded feels in usage always like hacky 😅

**Comment by nex3** [comment] 2022-08-15 20:51
@ntkme Maintainers will often find it quite annoying to have to deal with multiple issues knowingly filed for the same request, and annoying maintainers isn't a great way to get them to work on the things that you want. On the other hand, if the original issue gets enough :+1: reacts, you can take that to the maintainers on the mailing list or other means of communication and use it as evidence that this is in fact something that would provide substantial benefits.

**Comment by rubenwardy** [comment] 2023-01-08 23:00
If you got here from an error in Jekyll then the problem is caused by jekyll-sass-converter 3.0 switching from sassc to sass-embedded. They [recommend downgrading by adding the following to your Gemfile](https://github.com/jekyll/jekyll-sass-converter#migrate-from-2x-to-3x):

```
gem "jekyll-sass-converter", "~> 2.0"
```

Sorry for the bump, hopefully this comment should prevent you from receiving duplicate feature requests though
