### ISSUE TITLE
The compiler does not work on linux Alpine

### ISSUE THREAD

**Issue by alexander-xyz** [sass/dart-sass-embedded#86] opened 2022-05-19 13:07 UTC
Hi! Unfortunately, dart-sass-embedded binaries not working on linux Alpine.
```
# ./dart-sass-embedded 
./dart-sass-embedded: No such file or directory

# ldd ./dart-sass-embedded
        /lib64/ld-linux-x86-64.so.2 (0x7f6df5957000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f6df5957000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f6df5957000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f6df5957000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f6df5957000)
        ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f6df52cc000)
Error relocating ./dart-sass-embedded: __sbrk: symbol not found
```

Can you fix that?

**Comment by nex3** [comment] 2022-05-23 20:38
Duplicate of https://github.com/sass/dart-sass-embedded/issues/85

**Closed as completed by nex3** 2022-05-23 20:38 UTC
